In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow import keras

In [ ]:
from tensorflow.keras import layers

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
data=pd.read_csv("names.csv")

In [ ]:
data.head()

Id       Name    Year Gender   Count
0   1       Mary  1880.0      F  7065.0
1   2       Anna  1880.0      F  2604.0
2   3       Emma  1880.0      F  2003.0
3   4  Elizabeth  1880.0      F  1939.0
4   5     Minnie  1880.0      F  1746.0

In [ ]:
df1=data.drop(["Id","Year","Count"],axis=1)

In [ ]:
df1.head()

Name Gender
0       Mary      F
1       Anna      F
2       Emma      F
3  Elizabeth      F
4     Minnie      F

In [ ]:
df1.shape

(137909, 2)

In [ ]:
df1["Name"].unique()

array(['Mary', 'Anna', 'Emma', ..., 'Hensley', 'Herchell', nan],
      dtype=object)

In [ ]:
df1["Name"].unique().size

11180

In [ ]:
df1["Name"].nunique()

11179

In [ ]:
df1["Name"].value_counts()

Theo        74
Bennie      74
Louie       74
George      74
Johnnie     74
            ..
Leatta       1
Johnella     1
Luecile      1
Junette      1
Malda        1
Name: Name, Length: 11179, dtype: int64

In [ ]:
df1["Gender"].astype("category").cat.codes#we can use here getdummies but this is new way

0         0
1         0
2         0
3         0
4         0
         ..
137904    1
137905    1
137906    1
137907    1
137908   -1
Length: 137909, dtype: int8

In [ ]:
df1["Gender"]=df1["Gender"].astype("category").cat.codes

In [ ]:
df1.head()

Name  Gender
0       Mary       0
1       Anna       0
2       Emma       0
3  Elizabeth       0
4     Minnie       0

In [ ]:
gd1=df1.groupby("Name")

In [ ]:
df2=gd1.mean()

In [ ]:
df2.head()

Gender
Name           
Aage   1.000000
Aagot  0.000000
Aaron  0.948718
Ab     1.000000
Abb    1.000000

In [ ]:
df2.reset_index(inplace=True)

In [ ]:
df2.head()

Name    Gender
0   Aage  1.000000
1  Aagot  0.000000
2  Aaron  0.948718
3     Ab  1.000000
4    Abb  1.000000

In [ ]:
df2["Gender"]=df2["Gender"].astype("int")

In [ ]:
df2.head()

Name  Gender
0   Aage       1
1  Aagot       0
2  Aaron       0
3     Ab       1
4    Abb       1

In [ ]:
import string

In [ ]:
letters=list(string.ascii_lowercase)

In [ ]:
list(range(1,27))

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26]

In [ ]:
vocab=dict(zip(letters,range(1,27)))

In [ ]:
vocab

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26}

In [ ]:
vocab["n"]

14

In [ ]:
df2["Name"][0]

'Aage'

In [ ]:
n=[]
for i in df2["Name"][5]:
  num=vocab[i.lower()]
  n.append(num)
  
print(df2["Name"][5])
print(n) 


Abbey
[1, 2, 2, 5, 25]


In [ ]:
df2.shape

(11179, 2)

In [ ]:
df2.shape[0]

11179

In [ ]:
for i in range(1,10):
  print(df2["Name"][i])

Aagot
Aaron
Ab
Abb
Abbey
Abbie
Abbot
Abbott
Abby


In [ ]:
df2

Name  Gender
0         Aage       1
1        Aagot       0
2        Aaron       0
3           Ab       1
4          Abb       1
...        ...     ...
11174  Zygmont       1
11175  Zygmund       1
11176  Zygmunt       1
11177   Zylpha       0
11178  Zylphia       0

[11179 rows x 2 columns]

In [ ]:
def name_to_num():
  for i in range(0,df2.shape[0]):
    seq=[vocab[j.lower()]    for j in df2["Name"][i]]
    df2["Name"][i]=seq

In [ ]:
name_to_num()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [ ]:
df2.head()

Name  Gender
0        [1, 1, 7, 5]       1
1   [1, 1, 7, 15, 20]       0
2  [1, 1, 18, 15, 14]       0
3              [1, 2]       1
4           [1, 2, 2]       1

In [ ]:
X=df2["Name"].values

In [ ]:
y=df2["Gender"].values

In [ ]:
X

array([list([1, 1, 7, 5]), list([1, 1, 7, 15, 20]),
       list([1, 1, 18, 15, 14]), ..., list([26, 25, 7, 13, 21, 14, 20]),
       list([26, 25, 12, 16, 8, 1]), list([26, 25, 12, 16, 8, 9, 1])],
      dtype=object)

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
x=pad_sequences(df2["Name"].values,maxlen=10,padding="pre")

In [ ]:
x

array([[ 0,  0,  0, ...,  1,  7,  5],
       [ 0,  0,  0, ...,  7, 15, 20],
       [ 0,  0,  0, ..., 18, 15, 14],
       ...,
       [ 0,  0,  0, ..., 21, 14, 20],
       [ 0,  0,  0, ..., 16,  8,  1],
       [ 0,  0,  0, ...,  8,  9,  1]], dtype=int32)

In [ ]:
X[0]

[1, 1, 7, 5]

In [ ]:
x[0]

array([0, 0, 0, 0, 0, 0, 1, 1, 7, 5], dtype=int32)

# model_building

In [ ]:
inp=layers.Input(shape=(10,))

In [ ]:
emb=layers.Embedding(input_dim=27,output_dim=5)(inp)

In [ ]:
lstm1=layers.LSTM(units=32,return_sequences=True)(emb)

In [ ]:
lstm2=layers.LSTM(units=64)(lstm1)

In [ ]:
out=layers.Dense(units=1,activation="sigmoid")(lstm2)

In [ ]:
model=keras.Model(inputs=inp,outputs=out)

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 10)]              0         
_________________________________________________________________
embedding (Embedding)        (None, 10, 5)             135       
_________________________________________________________________
lstm (LSTM)                  (None, 10, 32)            4864      
_________________________________________________________________
lstm_1 (LSTM)                (None, 64)                24832     
_________________________________________________________________
dense (Dense)                (None, 1)                 65        
Total params: 29,896
Trainable params: 29,896
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [ ]:
model.fit(x,y,epochs=25,batch_size=256,validation_split=0.20)

Epoch 1/25
35/35 [==============================] - 1s 41ms/step - loss: 0.4158 - accuracy: 0.7954 - val_loss: 0.4046 - val_accuracy: 0.8055
Epoch 2/25
35/35 [==============================] - 1s 40ms/step - loss: 0.4140 - accuracy: 0.7985 - val_loss: 0.4047 - val_accuracy: 0.8010
Epoch 3/25
35/35 [==============================] - 1s 40ms/step - loss: 0.4132 - accuracy: 0.8005 - val_loss: 0.4057 - val_accuracy: 0.8064
Epoch 4/25
35/35 [==============================] - 1s 39ms/step - loss: 0.4129 - accuracy: 0.7992 - val_loss: 0.4043 - val_accuracy: 0.8077
Epoch 5/25
35/35 [==============================] - 1s 40ms/step - loss: 0.4105 - accuracy: 0.8017 - val_loss: 0.4058 - val_accuracy: 0.8077
Epoch 6/25
35/35 [==============================] - 1s 40ms/step - loss: 0.4090 - accuracy: 0.8036 - val_loss: 0.4052 - val_accuracy: 0.8077
Epoch 7/25
35/35 [==============================] - 1s 40ms/step - loss: 0.4065 - accuracy: 0.8038 - val_loss: 0.4086 - val_accuracy: 0.8095
Epoch 8/25
35

In [ ]:
name="john"

In [ ]:
s=[vocab[i.lower()] for i in name]
print(s)

[10, 15, 8, 14]


In [ ]:
test=pad_sequences([s],maxlen=10)

In [ ]:
test

array([[ 0,  0,  0,  0,  0,  0, 10, 15,  8, 14]], dtype=int32)

In [ ]:
p=model.predict(test)

In [ ]:
if p>=0.5:
  print(name,"is male")
else :
  print(name,"is female")

john is male
